services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/database-exercises
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/database_exercises
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: postgres:16.3-bookworm
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: database_exercises
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pg-data

volumes:
  pg-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/docker/db/data
      o: bind
